# Generated by Django 5.1.5 on 2025-02-05 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 13, 29, 37, 567101, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
