# Generated by Django 5.1.5 on 2025-02-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_availability_date_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration_minutes',
        ),
    ]
