# Generated by Django 5.1.5 on 2025-02-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='youremail@gmail.com', max_length=254),
        ),
    ]
