# Generated by Django 5.1.5 on 2025-02-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_patient_name_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='youremail@gmail.com', max_length=254),
        ),
    ]
