# Generated by Django 5.1.5 on 2025-02-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
